# localhost の 5432 番ポートに use: postgres/pass: password の DB サーバを立てる
# diesel 使う前には `export DATABASE_URL=postgresql://postgres:password@localhost:5432/log-collector`
postgres-data:
    image: busybox
    volumes:
        - /var/lib/postgresql/log-collector-data
    container_name: log-collector-postgres-datastore

postgresql:
    image: postgres
    environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: password
    ports:
        - "5432:5432"
    volumes_from:
        - postgres-data
